### ISSUE TITLE
executive (.exe) shows something other than download link

### ISSUE THREAD

**Issue by CodeNameSJ** [BDZNH/MIUI-Theme-Download-Link-Generator#5]
![image](https://user-images.githubusercontent.com/57455051/85750143-127cd580-b727-11ea-889a-8a575f4ea518.png)

**Comment by BDZNH** [comment]
@SJ-Shubh 试试看UWP版本。 win32 的乱码也是奇奇怪怪的。

**Comment by CodeNameSJ** [comment]
> @SJ-Shubh 试试看UWP版本。 win32 的乱码也是奇奇怪怪的。

I tried that version but it crashes when a link is pasted in box (after clicking generate button)

**Comment by BDZNH** [comment]
@SJ-Shubh what is the link look like ?

**Comment by CodeNameSJ** [comment]
> @SJ-Shubh what is the link look like 
Same in screenshot of this issue. But apparently some links work.
